#!/usr/bin/env python
import click
from aiohttp import web
from faker import Factory
from sqlalchemy import create_engine

from counter.utils.common import get_config, DEFAULT_CONFIG_PATH
from counter.models.pages.tables import pages

pass_app = click.make_pass_decorator(dict)


@click.group()
@click.version_option("1.0")
@click.pass_context
def cli(ctx):
    config = get_config(["-c", DEFAULT_CONFIG_PATH.as_posix()])
    fake = Factory.create()
    fake.seed(1234)
    db_url = 'postgresql+psycopg2://{user}:{password}@{host}:{port}/{database}'.format(**config['postgres'])
    engine = create_engine(db_url)
    app = {
        "config": config,
        "db": engine,
        "fake": fake
    }

    ctx.obj = app


@cli.command()
@pass_app
def seed_db(app):
    conn = app['db'].connect()
    for _ in range(100):
        insert_stmt = pages.insert().values(
            title=app["fake"].paragraph(nb_sentences=1),
            description=app["fake"].paragraph(nb_sentences=10),
        )
        conn.execute(insert_stmt)


if __name__ == "__main__":
    cli()
